parameters:
  name: ""
  displayName: ""
  clusterType: ""
  clusterName: "" # Recommended to pass in unique identifier
  vmSize: ""
  k8sVersion: ""
  windowsOsSku: ""
  dependsOn: ""
  region: ""

jobs:
  - job: ${{ parameters.name }}
    displayName: Cluster - ${{ parameters.name }}
    steps:
      - task: AzureCLI@1
        inputs:
          azureSubscription: $(AZURE_TEST_AGENT_SERVICE_CONNECTION)
          scriptLocation: "inlineScript"
          scriptType: "bash"
          addSpnToEnvironment: true
          inlineScript: |
            set -e
            mkdir -p ~/.kube/
            make -C ./hack/aks azcfg AZCLI=az REGION=${{ parameters.region }}
            make -C ./hack/aks ${{ parameters.clusterType }} AZCLI=az REGION=${{ parameters.region }} SUB=$(SUB_AZURE_NETWORK_AGENT_TEST) CLUSTER=${{ parameters.clusterName }} K8S_VER=${{ parameters.k8sVersion }} VM_SIZE=${{ parameters.vmSize }} WINDOWS_OS_SKU=${{ parameters.windowsOsSku }} WINDOWS_VM_SKU=${{ parameters.vmSize }} WINDOWS_USERNAME=${WINDOWS_USERNAME} WINDOWS_PASSWORD=${WINDOWS_PASSWORD}
            echo "Cluster successfully created"
        displayName: Cluster - ${{ parameters.clusterType }}
