parameters:
  name: ""
  displayName: ""
  clusterType: ""
  clusterName: ""
  dependsOn: ""

stages:
- stage: delete${{ parameters.clusterName }}
  condition: always()
  displayName: Delete Cluster - ${{ parameters.displayName }}
  dependsOn:
  - ${{ parameters.dependsOn }} # Stage prior to delete
  - ${{ parameters.clusterName }} # Requires matching create cluster stage defined by clusterName
  pool:
    name: $(BUILD_POOL_NAME_DEFAULT)
  jobs:
    - job: delete${{ parameters.name }}
      displayName: Delete - ${{ parameters.name }}
      pool:
        name: $(BUILD_POOL_NAME_DEFAULT)
      condition: always()
      steps:
        - task: AzureCLI@1
          inputs:
            azureSubscription: $(AZURE_TEST_AGENT_SERVICE_CONNECTION)
            scriptLocation: "inlineScript"
            scriptType: "bash"
            addSpnToEnvironment: true
            inlineScript: |
              set -e
              echo "Deleting cluster"
              make -C ./hack/aks azcfg AZCLI=az REGION=$(REGION_AKS_CLUSTER_TEST)
              make -C ./hack/aks set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(make revision)
              make -C ./hack/aks down AZCLI=az REGION=$(REGION_AKS_CLUSTER_TEST) SUB=$(SUB_AZURE_NETWORK_AGENT_TEST) CLUSTER=${{ parameters.clusterName }}-$(make revision)
              echo "Cluster and resources down"
          displayName: Cluster - ${{ parameters.clusterType }}
