name: golangci-lint
on:
  merge_group:
    types: [ checks_requested ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
jobs:
  golangci119:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, windows-latest]
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }} 
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.1
        args: --timeout=10m 
        only-new-issues: true
